"""
Central place for LLM, embedding, and vector-store configuration.

Every agent/script in this project should get its LLM or embeddings client
from `get_llm()` / `get_embeddings()` here rather than constructing one
itself. That keeps provider/model choice a one-file change as the project
grows (see ROADMAP.md).
"""

import os
from pathlib import Path
from typing import Optional

from dotenv import load_dotenv

# Load variables from a .env file in the project root, if present.
load_dotenv()

DEFAULT_MODEL = os.environ.get("GEMINI_MODEL", "gemini-3.5-flash")

# Gemini's stable, generally-available text embedding model. (There's a
# newer "gemini-embedding-2" multimodal model too, but its embedding space
# is incompatible with this one -- switching later means re-ingesting
# everything, so pin a version deliberately via GEMINI_EMBEDDING_MODEL
# rather than drifting to whatever is newest.)
DEFAULT_EMBEDDING_MODEL = os.environ.get(
    "GEMINI_EMBEDDING_MODEL", "models/gemini-embedding-001"
)

# --- Paths -------------------------------------------------------------

# src/knowledge_ops/config.py -> parents[0]=knowledge_ops, [1]=src, [2]=repo root
PROJECT_ROOT = Path(__file__).resolve().parents[2]

# Where source documents live (Phase 2). Currently just PDFs; the loader
# dispatches by file extension so other types can be dropped in later.
DOCUMENTS_DIR = Path(__file__).resolve().parent / "data" / "documents"

# Where the Chroma vector store is persisted (Phase 3). Git-ignored --
# it's fully regenerated by running the ingestion script.
CHROMA_PERSIST_DIR = PROJECT_ROOT / "chroma_db"
CHROMA_COLLECTION_NAME = os.environ.get("CHROMA_COLLECTION_NAME", "knowledge_ops")

# --- Chunking ------------------------------------------------------------

CHUNK_SIZE = int(os.environ.get("CHUNK_SIZE", "1000"))
CHUNK_OVERLAP = int(os.environ.get("CHUNK_OVERLAP", "150"))

# --- Orchestration (Phase 4+5: decomposition + multi-document RAG) ------

# How many chunks to retrieve per subtask. Total chunks fed to the final
# answer step is roughly (subtasks x this), so keep this modest.
TOP_K_PER_SUBTASK = int(os.environ.get("TOP_K_PER_SUBTASK", "4"))

# Hard ceiling on how many subtasks the decomposition step may produce,
# regardless of what the LLM proposes -- keeps a pathological/ambiguous
# question from fanning out into dozens of retrieval calls.
MAX_SUBTASKS = int(os.environ.get("MAX_SUBTASKS", "5"))

# --- Multi-agent architecture (Phase 5) ---------------------------------

# How many times the Reasoning agent may retry after a Validation agent
# rejection, per question. Bounded so an answer that can never satisfy
# validation (e.g. the documents genuinely don't cover it) doesn't loop
# forever -- after this many retries the last draft is returned as-is,
# with the validation verdict still logged to the trace either way.
MAX_REVISIONS = int(os.environ.get("MAX_REVISIONS", "1"))

# Where the Memory agent persists the audit trail of every run
# (logs/agent_trace.jsonl). Git-ignored -- it's local operational history,
# not project source.
LOGS_DIR = PROJECT_ROOT / "logs"

# --- Guardrails (Phase 6+7: explainability + governance) -----------------

# Input Guard agent: reject questions longer than this outright, before
# any LLM call is made.
MAX_QUESTION_LENGTH = int(os.environ.get("MAX_QUESTION_LENGTH", "2000"))

# Validation agent: an answer is treated as low-confidence -- and gets the
# same "unverified" warning as an outright rejection -- if the validator's
# self-reported confidence falls below this, even when it also said
# `approved: True`. Tune down if too many fine answers get flagged, up if
# clearly shaky ones aren't.
CONFIDENCE_THRESHOLD = float(os.environ.get("CONFIDENCE_THRESHOLD", "0.7"))

# --- Evaluation & failure detection (Phase 8) ---------------------------

# Evaluation agent: a subtask is flagged "insufficient_retrieval" if it
# comes back with fewer than this many chunks (0, by default -- a subtask
# that finds nothing at all is the one case we can flag with total
# confidence, regardless of the embedding space).
MIN_CHUNKS_PER_SUBTASK = int(os.environ.get("MIN_CHUNKS_PER_SUBTASK", "1"))

# Evaluation agent: an optional distance ceiling above which a retrieved
# chunk is considered "not actually relevant." Left unset by default --
# unlike MIN_CHUNKS_PER_SUBTASK, there's no safe universal default here:
# what counts as a "good" distance score depends on the embedding model
# and Chroma's distance function, and hasn't been empirically tuned for
# this project's real Gemini embeddings. Inspect real scores with
# `python run_search_demo.py` first, then set this via the
# RELEVANCE_DISTANCE_THRESHOLD env var if you want the extra check --
# leaving it unset means only the always-safe zero-chunks check runs.
_relevance_threshold_raw = os.environ.get("RELEVANCE_DISTANCE_THRESHOLD")
RELEVANCE_DISTANCE_THRESHOLD = (
    float(_relevance_threshold_raw) if _relevance_threshold_raw else None
)


def _require_api_key() -> str:
    api_key = os.environ.get("GOOGLE_API_KEY")
    if not api_key or api_key == "your-key-here":
        raise RuntimeError(
            "GOOGLE_API_KEY is not set. Copy .env.example to .env and add "
            "your key (get a free one at https://aistudio.google.com/apikey)."
        )
    return api_key


def get_llm(model: Optional[str] = None, temperature: float = 0.0):
    """Build and return a LangChain chat model client.

    Currently backed by Google Gemini (free tier, no credit card required).
    Swapping providers later (Anthropic, OpenAI, a local Ollama model)
    means changing this function, not every script that calls it.
    """
    api_key = _require_api_key()

    # Imported here so importing this module doesn't require the package
    # to be installed until an LLM is actually requested.
    from langchain_google_genai import ChatGoogleGenerativeAI

    return ChatGoogleGenerativeAI(
        model=model or DEFAULT_MODEL,
        temperature=temperature,
        google_api_key=api_key,
    )


def get_embeddings(model: Optional[str] = None):
    """Build and return a LangChain embeddings client (Google Gemini).

    Used by both the ingestion pipeline (embedding documents into Chroma)
    and, later, RAG query answering (embedding the user's question the
    same way so it lands in the same vector space).
    """
    api_key = _require_api_key()

    from langchain_google_genai import GoogleGenerativeAIEmbeddings

    return GoogleGenerativeAIEmbeddings(
        model=model or DEFAULT_EMBEDDING_MODEL,
        google_api_key=api_key,
    )
